### ISSUE TITLE
One-Click is still broken for ExH

### ISSUE THREAD

**Issue by HASJ** [DakuTree/userscripts#4]
Just reporting really not trying to be a bother.

**Comment by DakuTree** [comment]
Script seems to be working fine for me. Are you on the latest version (1.1.1)?

**Comment by DakuTree** [comment]
~~Oh wait never mind. Thought you meant E-Hentai & not EXHentai. I see what you mean with it not working, I'll try and get a quick fix out.~~

**Comment by DakuTree** [comment]
Disregard that. Was using an altered version of the script :\
1.1.1 seems to work on both EX & EH from what I can see.

**Comment by HASJ** [comment]
Weird. On EH it works as intended. On EX, if I click on archive download, it loads the archive download dialog on tab and that's it. If I have EH auto-start on, it'll start the archive normally but still on tab.
With or without any other script running.

Oh yeah, GM on Firefox.

**Comment by DakuTree** [comment]
That is really strange. If it works fine on EH there should be absolutely no reason it shouldn't work on EX since the code is the exact same.
Only thing I can think is another userscript/extension causing issues...

It might be worth reverting to 1.0.3 to see if that fixes the issue - https://greasyfork.org/en/scripts/1954-e-x-hentai-one-click-dl?version=55504

**Comment by HASJ** [comment]
Wow, apparently, my cookies were broken.
I reverted to 1.0.3, nothing. Back to 1.1.1, nothing. Deleted cookies, working.
I cleared them and then I didn't have enough GP/credits anymore... Looks like a bug was happening and I was downloading without paying for anything. I downloaded a L O T of stuff.

**Comment by DakuTree** [comment]
I'm guessing the zero GP/credits were probably the cause of the error.
The script assumes you always have enough to buy the gallery but has no fallbacks in case you don't.
I'll see about adding something to fix that.

As for why EH was working and EX wasn't, all EX archives cost double the GP they would on EH. So it's possible that you had just enough to buy from EH but not EX (since archive costs can get into 100K+ GP there).
