### ISSUE TITLE
MangaUpdates Better Lists: "Unable to Sync, are you logged in on MAL?"

### ISSUE THREAD

**Issue by Beylers** [DakuTree/userscripts#9]
Hi, when i click on the "I've read the latest chapter" button I always get the unable to sync MAL notification, even though I'm logged in on MAL. Do I need to input my MAL login details somewhere? Also is it possible to manually add the MAL IDs to the Mangaupdate end so that it recognizes which MU Manga belongs to which MAL Manga, I have some that link to the correct MAL Manga, like Boku No Hero, but most are unlinked. Thank you

**Comment by DakuTree** [comment]
The syncing issue should be fixed as of the above commit. Might need to manually update to get it right away (v1.4.1).  

As for manually adding MAL IDs, it isn't possible at the moment and there isn't any plans to add it as the script has been pretty much abandoned since last June when [MAL removed MU links](https://myanimelist.net/forum/?topicid=1517322), which effectively killed off auto-linking series.
